#FROM openjdk:17
#WORKDIR /home/dmtrung/springBoot/toeic-exam-app
#COPY target/ToeicExam-0.0.1-SNAPSHOT.jar /app.jar
#EXPOSE 8080
#CMD ["java", "-jar", "/app.jar"]
FROM ibm-semeru-runtimes:open-17-jdk
VOLUME /tmp
COPY target/ToeicExam-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080